services:
  contract:

    build: ./near-contract
  
    container_name: vc_smart_contracts
  
    image: smart_contracts:vc
  
    volumes:
      - ./near-contract/build:/contract/build
  
    environment:
      - NEAR_ENV=testnet

  frontend:
    container_name: vc_react_app

    build:
      context: ./react_app

    image: react_app:vc

    command: npm run dev

    ports:
      - 5173:5173

    env_file:
      - ./react_app/.env

    volumes:
      - ./react_app/:/react
      - node_modules:/react/node_modules

    networks:
      - vc_network

    develop:
      watch:
        - path: ./react_app/package.json
          action: rebuild
        - path: ./react_app/package-lock.json
          action: rebuild
        - path: ./react_app/Dockerfile
          action: rebuild

    depends_on:
      - contract

volumes:
  node_modules:

networks:
  vc_network:
    driver: bridge
